["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "."

["protostar.contracts"]
storage = ["./exercises/contracts/storage/ownableStorage.cairo"]

["protostar.build"]
cairo-path = ["./cairo_contracts/src"]